### ISSUE TITLE
OSC-CL2 Trino crashing

### ISSUE THREAD

**Issue by HumairAK** [operate-first/operations#466]
```
2022-04-11T15:17:13.587Z	ERROR	main	io.trino.server.Server	Configuration errors:

1) Error: Configuration property 'query.max-length' was not used

1 error
io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Configuration property 'query.max-length' was not used

1 error
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:232)
	at io.trino.plugin.iceberg.InternalIcebergConnectorFactory.createConnector(InternalIcebergConnectorFactory.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.trino.plugin.iceberg.IcebergConnectorFactory.create(IcebergConnectorFactory.java:59)
	at io.trino.connector.ConnectorManager.createConnector(ConnectorManager.java:403)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:252)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:241)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:227)
	at io.trino.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
	at io.trino.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at io.trino.server.Server.doStart(Server.java:128)
	at io.trino.server.Server.lambda$start$0(Server.java:80)
	at io.trino.$gen.Trino_373____20220411_151703_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:80)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)


2022-04-11T15:17:13.588Z	INFO	Thread-84	io.airlift.bootstrap.LifeCycleManager	JVM is shutting down, cleaning up
2022-04-11T15:17:13.588Z	INFO	Thread-85	io.airlift.bootstrap.LifeCycleManager	JVM is shutting down, cleaning up
```

Triggered by this pr: https://github.com/operate-first/apps/pull/1883

**Comment by MichaelTiemannOSC** [comment]
Yikes!  I don't know where this variable initialization belongs.  I thought I picked the right place, but obviously not. The Trino docs are HORRIBLE in this regard.  Trino itself references the variable when it's overrun, but the trino docs themselves don't say where it is set.  Maybe it's computed from other parameters?

**Comment by MichaelTiemannOSC** [comment]
Whelp, doesn't work:

```
trino:sandbox> set session query.max_length = 10000000;
Query 20220411_154202_00001_rw26j failed: line 1:1: Catalog 'query' does not exist
set session query.max_length = 10000000

trino:sandbox> set session query_max_length = 10000000;
Query 20220411_154216_00002_rw26j failed: line 1:1: Session property 'query_max_length' does not exist
set session query_max_length = 10000000
```

I did a `SHOW SESSION` command, but didn't see it as part of that list.

**Comment by erikerlandson** [comment]
most config parameters can be locally overridden by a corresponding session property, if one has permissions to set session properties, which I haven't looked into.  Allowing users to set these has potential risks since many parameters can cause performance problems if set improperly.  However we can investigate allowing some people access, for experimentation purposes.

Regardless, we need to figure out where these are set in the config files.

**Comment by erikerlandson** [comment]
I'd guess it was a coordinator property, but I agree with MT that the docs don't give a lot of guidance

**Comment by erikerlandson** [comment]
Have asked on the trino slack:
https://app.slack.com/client/TFKPX15NC/CGB0QHWSW/thread/CGB0QHWSW-1645042743.812489

**Comment by erikerlandson** [comment]
The trino people's guidance was: 
> Everything unless mentioned needs to be set in both coordinators and workers. Only things like security configs and global system level things (like overall cluster memory) are required only on coordinator.

**Comment by HumairAK** [comment]
https://github.com/operate-first/apps/pull/1890 was merged, no crash. :+1:

**Comment by MichaelTiemannOSC** [comment]
That's two things working better than at the start of the day ;-)

**Comment by HumairAK** [comment]
Resolved -- closing.
